language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

matrix:
  include:
  - os: linux
    name: Integration install
    python: 3.7
    install:
    - make --quiet install -C rnxcmp
    - python setup.py install
    - pip install $(basename $TRAVIS_REPO_SLUG)[tests]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR/tests
  - os: linux
    name: PEP8 MyPy Coverage
    python: 3.7
    install:
    - make --quiet install -C rnxcmp
    - pip install -e .[tests,io,cov]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov
    - coveralls
  - os: linux
    python: 3.6
  - os: osx
    language: minimal
    install:
    - make --quiet install -C rnxcmp
    - pip3 install -e .[tests,io]
# Windows image never starts, use AppVeyor
#  - os: windows
#    language: minimal
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
#    install:
#    - mingw32-make install CC=gcc -C rnxcmp
#    - pip install -e .[tests]


install: pip install -e .[tests,io]

script: pytest -r a -v

